# Linting via luacheck

name: Lint (luacheck)

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo recursively
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 30

      - name: Install LuaCheck
        run: |
          sudo apt-get install luarocks
          luarocks install --local luacheck

      - name: Run linter
        run: |
          $HOME/.luarocks/bin/luacheck .
